### ISSUE TITLE
Wrong description? (ForceGL20)

### ISSUE THREAD

**Issue by Stepman123** [KabanFriends/CraftGR#11]
Hello.
I apologize for writing this repository as the ForceGL20 repository is closed for communication.

All conditions specified in the description are met. There is GLFW error 65543 for MC 1.17-1.20. And, MC 1.16.5 works fine with Java 17 (Adoptium, zulu and others).
MC 1.17-1.20.4 with ForceGL20(Fabric) crashes without a message, but the crashlog indicates shader issues.

Can you look at the crashlog to see if I have the correct cause of the crash? 
Video card is Radeon 9600:
OpenGL 2.1.8545 Release with 110 extension
GLSL 1.20
OpenCL not supported

So the reason is that MC 1.17-1.20.4 with ForceGL20 does not support GLSL 1.20?

[crash-2024-05-04_23.10.50-client.txt](https://github.com/KabanFriends/CraftGR/files/15210936/crash-2024-05-04_23.10.50-client.txt)

**Comment by KabanFriends** [comment]
The problem here happens because Mojang updated Minecraft's built-in shaders to use the shader version that OpenGL 2.0 can't recognize.

It's only a matter of time before Mojang chages the game so much that simpl to downgrading to OpenGL 2.0 wouldn't fix the issue anymore. My general direction for ForceGL20 is that, as soon as this band-aid fix stops working, I will discontinue the support for the mod. However, this crash in particular seems relatively simple to fix, so I might update the mod soon.

Anyway, this is not the repository for ForceGL20, so I will be closing the issue. Please check the mod again later as there is a chance that I might update the mod in the future.

**Comment by Stepman123** [comment]
> The problem here happens because Mojang updated Minecraft's built-in shaders to use the shader version that OpenGL 2.0 can't recognize.

Have they updated older versions of minecraft?
I've tried LegacyLauncher, which can download snapshots, but that also doesn't work. 
https://web.archive.org/ would that help?
